"use client";
import {useEffect,useState} from "react";
import {connectWallet,createPolicy,evaluatePolicy,readPolicies,type EthereumProvider,type Policy} from "../lib/genlayer";
const short=(a:string)=>`${a.slice(0,6)}...${a.slice(-4)}`;
const label=(d:number)=>d===1?"QUALIFIED":d===0?"NOT QUALIFIED":"UNDETERMINED";
export default function Home(){
 const [wallet,setWallet]=useState<`0x${string}`|null>(null),[provider,setProvider]=useState<EthereumProvider|null>(null),[policies,setPolicies]=useState<Policy[]>([]);
 const [flight,setFlight]=useState(""),[date,setDate]=useState(""),[url,setUrl]=useState(""),[amount,setAmount]=useState("100"),[busy,setBusy]=useState(false),[active,setActive]=useState<string|null>(null),[msg,setMsg]=useState(""),[hash,setHash]=useState("");
 async function refresh(a=wallet){if(!a)return;try{setPolicies(await readPolicies(a));}catch(e){console.error(e)}}
 async function connect(){try{const r=await connectWallet();setWallet(r.address);setProvider(r.provider);await refresh(r.address);}catch(e){setMsg(e instanceof Error?e.message:"Wallet connection failed.")}}
 async function create(e:React.FormEvent){e.preventDefault();if(!wallet||!provider)return setMsg("Connect your wallet first.");if(!url.startsWith("https://"))return setMsg("Use an HTTPS flight-status source URL.");try{setBusy(true);setHash("");setMsg("Submitting policy transaction...");await createPolicy(wallet,provider,{flightNumber:flight,departureDate:date,sourceUrl:url,payoutAmount:amount},h=>{setHash(h);setMsg("Policy submitted. Waiting for finalization...")});setMsg("Policy created successfully.");setFlight("");setDate("");setUrl("");await refresh();}catch(e){setMsg(e instanceof Error?e.message:"Could not create policy.")}finally{setBusy(false)}}
 async function evaluate(id:string){if(!wallet||!provider)return setMsg("Connect your wallet first.");try{setBusy(true);setActive(id);setHash("");setMsg("GenLayer validators are checking the external evidence...");await evaluatePolicy(wallet,provider,id,h=>{setHash(h);setMsg("Evaluation submitted. Waiting for consensus and finalization...")});await refresh();setMsg("Evaluation complete.");}catch(e){setMsg(e instanceof Error?e.message:"Evaluation failed.")}finally{setBusy(false);setActive(null)}}
 useEffect(()=>{const p=(window as any).ethereum as EthereumProvider|undefined;if(!p)return;p.request({method:"eth_accounts"}).then((a)=>{const x=a as string[];if(x?.[0]){setWallet(x[0] as `0x${string}`);setProvider(p)}}).catch(()=>{});},[]);
 useEffect(()=>{if(wallet)refresh(wallet)},[wallet]);
 return <main className="shell">
  <nav className="nav"><div className="brand"><div className="mark"><i/><i/><i/></div><div><b>FlightGuard</b><small>Powered by GenLayer</small></div></div><button className="ghost" onClick={connect}>{wallet?short(wallet):"Connect wallet"}</button></nav>
  <section className="hero"><span className="eyebrow">REAL-WORLD DECISIONS ONCHAIN</span><h1>Flight protection,<br/><em>resolved by GenLayer.</em></h1><p>Create a flight protection policy and let a GenLayer Intelligent Contract evaluate live external evidence when a disruption occurs.</p></section>
  <section className="grid">
   <div className="card"><span className="eyebrow">01 / CREATE</span><h2>Protect a flight</h2><form onSubmit={create}><label>Flight number<input value={flight} onChange={e=>setFlight(e.target.value)} placeholder="BA75" required/></label><label>Departure date<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label>Flight-status source URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..." required/><small>Use an airline, airport, or reputable live flight-status page.</small></label><label>Protection amount<input value={amount} onChange={e=>setAmount(e.target.value)} required/></label><button className="primary" disabled={busy||!wallet}>{busy?"Processing...":"Create protection"}</button></form></div>
   <div className="card"><span className="eyebrow">02 / RESOLVE</span><h2>How GenLayer decides</h2><div className="steps"><div><b>01</b><strong>Retrieve</strong><p>The contract reads the supplied live source.</p></div><div><b>02</b><strong>Interpret</strong><p>An LLM extracts the relevant flight outcome.</p></div><div><b>03</b><strong>Consensus</strong><p>Validators independently reproduce the decision.</p></div><div><b>04</b><strong>Record</strong><p>The agreed result is stored in the contract.</p></div></div></div>
  </section>
  {msg&&<section className="status"><span className="dot"/><div><b>Transaction status</b><p>{msg}</p>{hash&&<code>{hash}</code>}</div></section>}
  <section className="policies"><div className="sectionTitle"><div><span className="eyebrow">03 / YOUR POLICIES</span><h2>Flight protection dashboard</h2></div><button className="ghost" onClick={()=>refresh()}>Refresh</button></div>{!wallet?<div className="empty">Connect your wallet to view policies.</div>:policies.length===0?<div className="empty">No policies yet. Create your first flight protection above.</div>:<div className="list">{policies.map(p=><article className="policy" key={p.policy_id}><div className="top"><div><small>POLICY #{p.policy_id}</small><h3>{p.flight_number}</h3><p>{p.departure_date}</p></div><span className={`badge d${p.decision}`}>{label(p.decision)}</span></div><div className="data"><div><small>Protection</small><b>{p.payout_amount}</b></div><div><small>Contract state</small><b>{p.status}</b></div></div>{p.summary&&<div className="evidence"><small>Resolution summary</small><p>{p.summary}</p>{p.evidence&&<><small>Evidence excerpt</small><p>{p.evidence}</p></>}</div>}<div className="actions">{p.decision===-1&&<button className="primary small" disabled={busy} onClick={()=>evaluate(p.policy_id)}>{active===p.policy_id?"Evaluating...":"Evaluate with GenLayer"}</button>}<a className="ghost" href={p.source_url} target="_blank" rel="noreferrer">View source</a></div></article>)}</div>}</section>
  <footer><span>FlightGuard · GenLayer Intelligent Contract demo</span><span>Protection metadata only · no real funds are transferred</span></footer>
 </main>;
}
